name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: jameshenry/publish-shell-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
